config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'cleaner#new'

  resources :cleaner
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def index 
    end 

    def new 

    end 

end

app/controllers/cleaner_controller.rb
class CleanerController < ApplicationController

    def new

       


    end 


    def create 
    
        @script = params[:cleaner][:script]
        
        @splitted = @script.split("\n")
        count = 0
        tc = ""
        @loops = Hash.new

        @splitted.each{
            |element|
            
            if count % 4 == 1 
            
                tc = "00."+element[3..4].to_s+"."+element[6..7].to_s
   
            
            elsif count % 4 == 2 
             
                eng_dialog = element 
                current = @loops[tc].to_s
                @loops[tc] = current +" "+ eng_dialog
                
            end 
        
            count+= 1 
        
        }

        @loops.each{

            |t, d|
        
        
            puts t + d
          
        
        }
        



    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cleaner_helper.rb
module CleanerHelper
end

app/views/cleaner/create.html.erb
<div class="container">
    <table id="script">
        <tr>
            <th>TC</th>
            <th>Personaje</th>
            <th>English</th>
            <th>Diálogo<th>
        </tr>
        
        <% @loops.each do |tc, value|%>
        
            <tr>
                <td class="timecode_text"> <%= tc %>  </td>
                <td></td>
                <td class="english_text"> <%= value %> </td>
                <td></td>
            </tr>

        <% end %>

    </table>

</div>

app/views/cleaner/index.html.erb
<table>
    <tr>
        <th>TC</th>
        <th>Personaje</th>
        <th>English</th>
        <th>Diálogo<th>
    </tr>
    <tr>
        <td class="timecode_text">00.00.00</td>
        <td></td>
        <td class="english_text">"etc ect ect ect</td>
        <td></td>
    </tr>
</table>

<div>

    <%=
        @script
    %>

</div>

app/views/cleaner/new.html.erb
<div class="container-script">

    <%= form_for(:cleaner, url: cleaner_index_path) do |f| %>
 
        <%= f.label :script %>
        <%= f.text_area :script, class: "text-area" %>  

        <%= f.submit "Submit", class: "button"%>
        <%= submit_tag("Start Over", { :name => 'reset', :id => 'reset_button', :type => "reset" }) %>
    <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NgcsCs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>